_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 0cdfa2a8-964f-499c-ae0c-8f4843315bc7
name: 'demo prod'
mail: isabelle.michiels@smals.be
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
